### ISSUE TITLE
Placeholder status message not used

### ISSUE THREAD

**Issue by RedstoneFuture** [Dart2112/AFKPlusPAPI#9]
With the last version, the `%AFKPlus_Status%` placeholder is not converted to the message as defined in the `Afkpluspapi/config.yml` file.

```
#The values for AFKPlus_Status
status:
  #If the player is AFK
  true: "&7(AFK)"
  #If the player isn't afk
  false: ""
```

![grafik](https://github.com/user-attachments/assets/30307bac-e6f9-46b5-805a-b8ac3ee2b3c4)

Replicable with `/papi parse <username> %AFKPlus_Status%` --> `TRUE` or `FALSE`

- AFKPlus version 3.4.5
- AFKPlusPAPI version 1.0.6
- PlaceholderAPI version 2.11.6
- PaperMC 1.21.1
